version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mysqldb
    environment:
      POSTGRES_DB: envanter_db
      POSTGRES_USER: efsora_user
      POSTGRES_PASSWORD: efsora123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - efsora-network

volumes:
  postgres_data:

networks:
  efsora-network:
    driver: bridge
