services:
  - type: web
    name: envanter-yonetimi-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: JWT_REFRESH_EXPIRATION
        value: "604800000"
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://efsora-frontend-m3ke.onrender.com
      - key: APP_BACKEND_PUBLIC_URL
        value: https://envanter-yonetimi-backend.onrender.com
